adjective1 = input("Enter an adjective:\n")
adjective2 = input("Enter a positive adjective:\n")
adjective3 = input("Enter a negative adjective:\n")
adjective4 = input("Enter a second negative adjective:\n")
adjective5 = input("Enter a third negative adjective:\n")
noun1 = input("Enter a noun:\n")
celebrity1 = input("Enter the name of a celebrity:\n")
celebrity2 = input("Enter the name of a second celebrity:\n")
tvshow1 = input("Enter the name of a tvshow:\n")

print("There once was a", adjective1,"house.")
print("That there house was owned by old man", celebrity1)
print("They say old man",celebrity1,"used to be",adjective2,", but now he's",adjective3,",",adjective4,",and",adjective5,sep=" ")
print("A",noun1,"flew over the", adjective1, "house")
print(adjective3,",",adjective4,",",adjective5,",",celebrity1,"had a heart attack on their porch and died of shock.")
print("Old man", celebrity1, "had a long lost twin named", celebrity2,"that suddenly appreared in the next room")
print(celebrity2,"took over the as the star of,",tvshow1,"after",celebrity1,"'s tragic passing.")
